// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using YSecOps.Events.EfCore.Models;
#nullable enable

namespace YSecOps.Events.EfCore.Contexts
{
    public partial class YSecOpsEventStoreContext : DbContext
    {
        public YSecOpsEventStoreContext(DbContextOptions<YSecOpsEventStoreContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Event> Events { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.EventConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
