// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using YoumaconSecurityOps.Core.Shared.Models.Readers;
using YoumaconSecurityOps.Data.EntityFramework.Context;
using YoumaconSecurityOps.Data.EntityFramework.Models;

#nullable disable

namespace YoumaconSecurityOps.Data.EntityFramework.Context.Configurations
{
    public partial class RadioScheduleConfiguration : IEntityTypeConfiguration<RadioScheduleReader>
    {
        public void Configure(EntityTypeBuilder<RadioScheduleReader> entity)
        {
            entity.ToTable("RadioSchedule");

            entity.HasKey(e => e.Id);

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.SysEnd).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.SysStart).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.LastStaffToHave)
                .WithMany(p => p.RadioSchedules)
                .HasForeignKey(d => d.LastStaffToHave_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RadioSchedule_Staff");

            entity.HasOne(d => d.Location)
                .WithMany(p => p.RadioSchedule)
                .HasForeignKey(d => d.Location_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RadioSchedule_Location");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RadioScheduleReader> entity);
    }
}
