// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using YoumaconSecurityOps.Core.Shared.Models.Readers;
using YoumaconSecurityOps.Data.EntityFramework.Context;
using YoumaconSecurityOps.Data.EntityFramework.Models;

#nullable disable

namespace YoumaconSecurityOps.Data.EntityFramework.Context.Configurations
{
    public partial class RoomScheduleConfiguration : IEntityTypeConfiguration<RoomScheduleReader>
    {
        public void Configure(EntityTypeBuilder<RoomScheduleReader> entity)
        {
            entity.ToTable("RoomSchedule");

            entity.HasKey(e => e.Id);

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.NumberOfKeys).HasDefaultValueSql("((1))");

            entity.Property(e => e.LocationId)
                .HasColumnName("Location_Id");

            entity.Property(e => e.LastStaffInRoomId)
                .HasColumnName("LastStaffInRoom_Id");

            entity.HasOne(d => d.LastStaffInRoom)
                .WithMany(p => p.RoomSchedules)
                .HasForeignKey(d => d.LastStaffInRoomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoomSchedule_Staff");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RoomScheduleReader> entity);
    }
}
