// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using YoumaconSecurityOps.Core.Shared.Models.Readers;

namespace YoumaconSecurityOps.Data.EntityFramework.Context.Configurations
{
    public partial class ShiftConfiguration : IEntityTypeConfiguration<ShiftReader>
    {
        public void Configure(EntityTypeBuilder<ShiftReader> entity)
        {
            entity.ToTable("Shifts");

            entity.HasKey(e => e.Id);

            entity.Property(e => e.StartingLocationId)
                .HasColumnName("StartingLocation");

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.SysEnd).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.SysStart).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.CurrentLocation)
                .WithMany(l => l.ShiftCurrentLocation)
                .HasForeignKey(d => d.CurrentLocationId)
                .HasPrincipalKey(l => l.Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Shifts_CurrentLocation");

            entity.HasOne(d => d.StaffMember)
                .WithMany(p => p.Shifts)
                .HasForeignKey(d => d.StaffId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Shifts_Staff");

            entity.HasOne(d => d.StartingLocationNavigation)
                .WithMany(p => p.ShiftStartingLocationNavigation)
                .HasForeignKey(d => d.StartingLocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Shifts_StartingLocation");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ShiftReader> entity);
    }
}
