// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using YoumaconSecurityOps.Core.Shared.Models.Readers;

namespace YoumaconSecurityOps.Data.EntityFramework.Context.Configurations
{
    public partial class StaffTypesRoleConfiguration : IEntityTypeConfiguration<StaffTypesRoles>
    {
        public void Configure(EntityTypeBuilder<StaffTypesRoles> entity)
        {
            entity.ToTable("StaffTypesRoles");

            entity.HasKey(e => e.Id)
                .IsClustered(false);

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.StaffTypeId)
                .HasColumnName("StaffType");

            entity.Property(e => e.RoleId)
                .HasColumnName("RoleId");

            entity.HasOne(d => d.Role)
                .WithMany(p => p.StaffTypeRoleMap)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StaffTypesRoles_Roles");

            entity.HasOne(d => d.Staff)
                .WithMany(p => p.StaffTypeRoleMaps)
                .HasForeignKey(d => d.StaffId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StaffTypesRoles_Staff");

            entity.HasOne(d => d.StaffTypeNavigation)
                .WithMany(p => p.StaffTypeRoleMaps)
                .HasForeignKey(d => d.StaffTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StaffTypesRoles_StaffTypes");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<StaffTypesRoles> entity);
    }
}
