// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using YoumaconSecurityOps.Core.Shared.Models.Readers;

#nullable disable

namespace YoumaconSecurityOps.Data.EntityFramework.Context.Configurations
{
    public partial class WatchListConfiguration : IEntityTypeConfiguration<WatchListReader>
    {
        public void Configure(EntityTypeBuilder<WatchListReader> entity)
        {
            entity.ToTable("WatchList");

            entity.HasKey(e => e.Id);
            
            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newsequentialid())");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WatchListReader> entity);
    }
}
