// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace YsecItAuthApp.Web.EntityFramework.Models
{
    [Table("UserRoleMap")]
    [Index(nameof(RoleId), Name = "IX_UserRoleMap_RoleId")]
    [Index(nameof(UserId), Name = "IX_UserRoleMap_UserId")]
    public partial class UserRoleMap
    {
        [Key]
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public int RoleId { get; set; }
        public DateTime CreatedAt { get; set; }
        [Required]
        public bool? IsActive { get; set; }
    }
}