// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.AspNetCore.Identity;

namespace YsecItAuthApp.Web.EntityFramework.Models
{
    /// <summary>
    /// Holding class for application level roles.
    /// </summary>
    public partial class YsecItRole: IdentityRole<Guid>
    {
        /// <value>
        /// Describes the role's permissions in detail
        /// </value>
        public string Description { get; set; }
    }
}