// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace YsecItAuthApp.Web.EntityFramework.Models
{
    /// <summary>
    /// Holding class for each user of the application. 
    /// </summary>
    [Index(nameof(UserName), Name = "AK_Users_UserName", IsUnique = true)]
    [Index(nameof(CreatedAt), Name = "IX_Users_CreatedAt")]
    public partial class YsecItUser: IdentityUser<Guid>
    {
        /// <value>
        /// Date and time the user was created
        /// </value>
        public DateTime CreatedAt { get; set; }
        
        /// <value>
        /// The YsecItUser's first name
        /// </value>
        [Required]
        [StringLength(100)]
        public string FirstName { get; set; } = default!;
        
        /// <value>
        /// The user's last name
        /// </value>
        [Required]
        [StringLength(100)]
        public string LastName { get; set; } = default!;

        /// <value>
        /// The salt for the stored password - and works with the stored hash
        /// </value>
        /// <remarks><see cref="IdentityUser{TKey}"/></remarks>
        [Required]
        [MaxLength(128)]
        public byte[] PasswordSalt { get; set; } = default!;
    }
}