// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace YoumaconSecurityOps.Shared.Models.Procedures;
public partial class p_AddStaffRolesResult
{
}

