// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using YsecItAuthApp.Web.EntityFramework.Context;
using YsecItAuthApp.Web.EntityFramework.Models;

#nullable disable

namespace YsecItAuthApp.Web.EntityFramework.Context.Configurations
{
    public partial class YsecItUserConfiguration : IEntityTypeConfiguration<YsecItUser>
    {
        public void Configure(EntityTypeBuilder<YsecItUser> entity)
        {
            entity.ToTable("Users");

            entity.HasKey(e => e.Id)
                .HasName("PK_User_Id");

            entity.Property(e => e.Id)
                .HasDefaultValue(Guid.NewGuid());

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<YsecItUser> entity);
    }
}
