// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace YSecOps.Data.EfCore.Models;

public partial class BannedList
{
    public Guid Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Reason { get; set; }
    public DateTime? LastSeenAt { get; set; }
}