// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace YSecOps.Data.EfCore.Models;

public partial class Incident
{
    public Guid Id { get; set; }
    public Guid RecordedBy_Id { get; set; }
    public Guid OpsManager_Id { get; set; }
    public Guid Shift_Id { get; set; }
    public Guid Location_Id { get; set; }
    public int Severity { get; set; }
    public DateTime RecordedOn { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Keywords { get; set; }
    public bool IsFollowUpRequired { get; set; }
    public string FollowUpResponse { get; set; }
    public string Injuries { get; set; }
    public DateTime? ResolvedAt { get; set; }
}