// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace YSecOps.Data.EfCore.Models;

public partial class Location
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public bool IsHotel { get; set; }
}