// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace YSecOps.Data.EfCore.Models;

public partial class NonStaffPeople
{
    public Guid Id { get; set; }
    public Guid IncidentId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Alias { get; set; }
    public long PhoneNumber { get; set; }
    public int PronounId { get; set; }
    public string Email { get; set; }
}