// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace YSecOps.Data.EfCore.Models;

public partial class Pronoun
{
    public int Id { get; set; }
    public string Name { get; set; }
}