// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace YSecOps.Data.EfCore.Models;

public partial class RadioSchedule
{
    public Guid Id { get; set; }
    public Guid LastStaffToHave_Id { get; set; }
    public Guid Location_Id { get; set; }
    public string RadioNumber { get; set; }
    public DateTime? CheckedOutAt { get; set; }
    public DateTime? CheckedInAt { get; set; }
    public bool? IsCharging { get; set; }
}