// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace YSecOps.Data.EfCore.Models
{
    public partial class Role
    {
        public int Id { get; set; }
        public string Role1 { get; set; }
    }
}