// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace YSecOps.Data.EfCore.Models
{
    public partial class Shift
    {
        public Guid Id { get; set; }
        public Guid StaffId { get; set; }
        public DateTime EndAt { get; set; }
        public DateTime StartAt { get; set; }
        public Guid StartingLocationId { get; set; }
        public Guid CurrentLocationId { get; set; }
        public DateTime? CheckedInAt { get; set; }
        public DateTime? CheckedOutAt { get; set; }
        public DateTime? LastReportedAt { get; set; }
        public string Notes { get; set; }
    }
}