// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace YSecOps.Data.EfCore.Models;

public partial class StaffTypesRole
{
    public Guid Id { get; set; }
    public Guid StaffId { get; set; }
    public int StaffTypeId { get; set; }
    public int RoleId { get; set; }
}