// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace YSecOps.Data.EfCore.Models;

public partial class Staff
{
    public Guid Id { get; set; }
    public bool IsOnBreak { get; set; }
    public bool NeedsCrashSpace { get; set; }
    public bool IsBlackShirt { get; set; }
    public bool IsRaveApproved { get; set; }
    public DateTime? BreakStartAt { get; set; }
    public DateTime? BreakEndAt { get; set; }
    public string ShirtSize { get; set; }
    public Guid? IncidentId { get; set; }
    public Guid? RoomId { get; set; }
}