// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace YoumaconSecurityOps.Core.Shared.Contexts.Configurations;

public partial class BannedListConfiguration : IEntityTypeConfiguration<BannedList>
{
    public void Configure(EntityTypeBuilder<BannedList> entity)
    {
        entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<BannedList> entity);
}