// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace YoumaconSecurityOps.Core.Shared.Contexts.Configurations;

    public partial class ContactConfiguration : IEntityTypeConfiguration<ContactReader>
    {
        public void Configure(EntityTypeBuilder<ContactReader> entity)
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Pronoun_Id).HasDefaultValueSql("((14))");

            entity.HasOne(d => d.Pronoun)
                .WithMany(p => p.Contacts)
                .HasForeignKey(d => d.Pronoun_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Contacts_Pronouns_Id");

            entity.HasOne(d => d.Staff)
                .WithOne(p => p.ContactInformation)
                .HasForeignKey<ContactReader>(d => d.Staff_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Contacts_Staff_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContactReader> entity);
    }