// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace YoumaconSecurityOps.Core.Shared.Contexts.Configurations;

public partial class IncidentConfiguration : IEntityTypeConfiguration<IncidentReader>
{
    public void Configure(EntityTypeBuilder<IncidentReader> entity)
    {
        entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

        entity.HasOne(d => d.Location)
            .WithMany(p => p.Incidents)
            .HasForeignKey(d => d.Location_Id)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Incidents_Locations_LocationId");

        entity.HasOne(d => d.OpsManager)
            .WithMany(p => p.IncidentOpsManagers)
            .HasForeignKey(d => d.OpsManager_Id)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Incidents_Staff_OpsManagerId");

        entity.HasOne(d => d.RecordedBy)
            .WithMany(p => p.IncidentRecordedBies)
            .HasForeignKey(d => d.RecordedBy_Id)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Incidents_Staff_RecordedBy");

        entity.HasOne(d => d.ShiftReader)
            .WithMany(p => p.Incidents)
            .HasForeignKey(d => d.Shift_Id)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Incidents_Shifts_ShiftId");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<IncidentReader> entity);
}