// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace YoumaconSecurityOps.Core.Shared.Contexts.Configurations;

public partial class NonStaffPeopleConfiguration : IEntityTypeConfiguration<NonStaffPeople>
{
    public void Configure(EntityTypeBuilder<NonStaffPeople> entity)
    {
        entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

        entity.HasOne(d => d.IncidentReader)
            .WithMany(p => p.NonStaffPeoples)
            .HasForeignKey(d => d.IncidentId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_NonStaff_Incidents_Id");

        entity.HasOne(d => d.Pronoun)
            .WithMany(p => p.NonStaffPeoples)
            .HasForeignKey(d => d.PronounId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_NonStaff_Pronouns_Id");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<NonStaffPeople> entity);
}