// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace YoumaconSecurityOps.Core.Shared.Contexts.Configurations;

public partial class RadioScheduleConfiguration : IEntityTypeConfiguration<RadioScheduleReader>
{
    public void Configure(EntityTypeBuilder<RadioScheduleReader> entity)
    {
        entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

        entity.Property(e => e.IsCharging).HasDefaultValueSql("((0))");

        entity.HasOne(d => d.LastStaffToHave)
            .WithMany(p => p.RadioSchedules)
            .HasForeignKey(d => d.LastStaffToHave_Id)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_RadioSchedule_Staff");

        entity.HasOne(d => d.Location)
            .WithMany(p => p.RadioSchedules)
            .HasForeignKey(d => d.Location_Id)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_RadioSchedule_Location");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<RadioScheduleReader> entity);
}
