// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace YoumaconSecurityOps.Core.Shared.Contexts.Configurations;

public partial class RoomScheduleConfiguration : IEntityTypeConfiguration<RoomScheduleReader>
{
    public void Configure(EntityTypeBuilder<RoomScheduleReader> entity)
    {
        entity.ToTable(tb => tb.IsTemporal(ttb =>
{
    ttb.UseHistoryTable("RoomSchedule_HISTORY", "dbo");
    ttb
        .HasPeriodStart("SysStart")
        .HasColumnName("SysStart");
    ttb
        .HasPeriodEnd("SysEnd")
        .HasColumnName("SysEnd");
}
));

        entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

        entity.Property(e => e.NumberOfKeys).HasDefaultValueSql("((1))");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<RoomScheduleReader> entity);
}
