// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace YoumaconSecurityOps.Core.Shared.Contexts.Configurations;

public partial class StaffConfiguration : IEntityTypeConfiguration<StaffReader>
{
    public void Configure(EntityTypeBuilder<StaffReader> entity)
    {
        entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

        entity.Property(e => e.NeedsCrashSpace).HasDefaultValueSql("((1))");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<StaffReader> entity);
}
