// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace YoumaconSecurityOps.Core.Shared.Contexts.Configurations;

public partial class StaffTypesRoleConfiguration : IEntityTypeConfiguration<StaffTypesRole>
{
    public void Configure(EntityTypeBuilder<StaffTypesRole> entity)
    {
        entity.HasKey(e => e.Id)
            .IsClustered(false);

        entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

        entity.HasOne(d => d.StaffRole)
            .WithMany(p => p.StaffTypesRoles)
            .HasForeignKey(d => d.RoleId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_StaffTypesRoles_Roles");

        entity.HasOne(d => d.Staff)
            .WithMany(p => p.StaffTypesRoles)
            .HasForeignKey(d => d.StaffId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_StaffTypesRoles_Staff");

        entity.HasOne(d => d.StaffType)
            .WithMany(p => p.StaffTypesRoles)
            .HasForeignKey(d => d.StaffTypeId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_StaffTypesRoles_StaffTypes");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<StaffTypesRole> entity);
}
