// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace YoumaconSecurityOps.Core.Shared.Context.Configurations;

public partial class BannedListConfiguration : IEntityTypeConfiguration<BannedListReader>
{
    public void Configure(EntityTypeBuilder<BannedListReader> entity)
    {
        entity.ToTable("BannedList");

        entity.HasKey(e => e.Id);

        entity.Property(e => e.Id)
            .HasDefaultValueSql("(newsequentialid())");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<BannedListReader> entity);
}
