// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace YoumaconSecurityOps.Core.Shared.Context.Configurations;

public partial class ContactConfiguration : IEntityTypeConfiguration<ContactReader>
{
    public void Configure(EntityTypeBuilder<ContactReader> entity)
    {
        entity.ToTable("Contacts");

        entity.HasKey(e => e.Id);

        entity.Property(e => e.Id)
            .HasDefaultValueSql("(newsequentialid())");

        entity.Property(e => e.CreatedOn)
            .HasDefaultValueSql("(getdate())");

        entity.HasOne(d => d.StaffMember)
            .WithOne(p => p.Contact)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Contacts_Staff_Id");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<ContactReader> entity);
}

