// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace YoumaconSecurityOps.Core.Shared.Context.Configurations;

public partial class IncidentConfiguration : IEntityTypeConfiguration<IncidentReader>
{
    public void Configure(EntityTypeBuilder<IncidentReader> entity)
    {
        entity.ToTable("Incidents");

        entity.HasKey(e => e.Id);

        entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

        entity.Property(e => e.Severity)
            .HasConversion(s => (int)s, val => (Severity)val)
            .HasColumnName("Severity");

        entity.HasOne(d => d.Location)
            .WithMany(p => p.Incidents)
            .HasForeignKey(d => d.LocationId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Incidents_Locations");

        entity.HasOne(d => d.RecordedBy)
            .WithMany(p => p.IncidentRecordedBy)
            .HasForeignKey(d => d.RecordedById)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Incidents_RecordedBy");

        entity.HasOne(d => d.ReportedBy)
            .WithMany(p => p.IncidentReportedBy)
            .HasForeignKey(d => d.ReportedById)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Incidents_ReportedBy");

        entity.HasOne(d => d.Shift)
            .WithMany(p => p.Incidents)
            .HasForeignKey(d => d.ShiftId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Incidents_Shifts");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<IncidentReader> entity);
}

