// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace YoumaconSecurityOps.Core.Shared.Context.Configurations;

public partial class StaffConfiguration : IEntityTypeConfiguration<StaffReader>
{
    public void Configure(EntityTypeBuilder<StaffReader> entity)
    {
        entity.ToTable("Staff");

        entity.HasKey(e => e.Id);

        entity.Property(e => e.Id)
            .HasDefaultValueSql("(newsequentialid())");

        entity.Property(e => e.NeedsCrashSpace).HasDefaultValueSql("((1))");
        
        entity.HasMany(s => s.StaffTypeRoleMaps)
            .WithOne(p => p.Staff)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_StaffTypesRoles_Staff");
        
        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<StaffReader> entity);
}
