// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace YoumaconSecurityOps.Core.Shared.Context.Configurations;

public partial class WatchListConfiguration : IEntityTypeConfiguration<WatchListReader>
{
    public void Configure(EntityTypeBuilder<WatchListReader> entity)
    {
        entity.ToTable("WatchList");

        entity.HasKey(e => e.Id);

        entity.Property(e => e.Id)
            .HasDefaultValueSql("(newsequentialid())");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<WatchListReader> entity);
}
