// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace YSecOps.Data.EfCore.Contexts.Configurations;
public partial class BannedListConfiguration : IEntityTypeConfiguration<BannedList>
{
    public void Configure(EntityTypeBuilder<BannedList> entity)
    {
        entity.ToTable("BannedList");

        entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

        entity.Property(e => e.FirstName)
            .IsRequired()
            .HasMaxLength(100);

        entity.Property(e => e.LastName)
            .IsRequired()
            .HasMaxLength(100);

        entity.Property(e => e.Reason)
            .IsRequired()
            .HasMaxLength(1000);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<BannedList> entity);
}