// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace YSecOps.Data.EfCore.Contexts.Configurations;

    public partial class IncidentConfiguration : IEntityTypeConfiguration<Incident>
    {
        public void Configure(EntityTypeBuilder<Incident> entity)
        {
            entity.HasIndex(e => e.OpsManager_Id, "IX_Incidents_OpsManagerId");

            entity.HasIndex(e => e.RecordedBy_Id, "IX_Incidents_RecordedBy");

            entity.HasIndex(e => new { e.RecordedOn, e.Severity }, "IX_Incidents_Severity");

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000);

            entity.Property(e => e.FollowUpResponse).HasMaxLength(1000);

            entity.Property(e => e.Injuries).HasMaxLength(1000);

            entity.Property(e => e.Keywords)
                .IsRequired()
                .HasMaxLength(500);

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(1000);

            entity.HasOne(d => d.Location)
                .WithMany(p => p.Incidents)
                .HasForeignKey(d => d.Location_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Incidents_Locations_LocationId");

            entity.HasOne(d => d.OpsManager)
                .WithMany(p => p.IncidentOpsManagers)
                .HasForeignKey(d => d.OpsManager_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Incidents_Staff_OpsManagerId");

            entity.HasOne(d => d.RecordedBy)
                .WithMany(p => p.IncidentRecordedBies)
                .HasForeignKey(d => d.RecordedBy_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Incidents_Staff_RecordedBy");

            entity.HasOne(d => d.Shift)
                .WithMany(p => p.Incidents)
                .HasForeignKey(d => d.Shift_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Incidents_Shifts_ShiftId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Incident> entity);
    }