// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using YSecOps.Data.EfCore.Contexts;
using YSecOps.Data.EfCore.Models;

namespace YSecOps.Data.EfCore.Contexts.Configurations
{
    public partial class NonStaffPeopleConfiguration : IEntityTypeConfiguration<NonStaffPeople>
    {
        public void Configure(EntityTypeBuilder<NonStaffPeople> entity)
        {
            entity.ToTable("NonStaffPeople");

            entity.HasIndex(e => e.IncidentId, "IX_NonStaffPeople_IncidentId");

            entity.HasIndex(e => new { e.LastName, e.FirstName }, "IX_NonStaffPeople_LastName_FirstName");

            entity.HasIndex(e => e.PronounId, "IX_NonStaffPeople_PronounId");

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.Alias)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);

            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NonStaffPeople> entity);
    }
}
