// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace YSecOps.Data.EfCore.Contexts.Configurations;

public partial class NonStaffPersonConfiguration : IEntityTypeConfiguration<NonStaffPerson>
{
    public void Configure(EntityTypeBuilder<NonStaffPerson> entity)
    {
        entity.HasIndex(e => e.IncidentId, "IX_NonStaffPeople_IncidentId");

        entity.HasIndex(e => new { e.LastName, e.FirstName }, "IX_NonStaffPeople_LastName_FirstName");

        entity.HasIndex(e => e.PronounId, "IX_NonStaffPeople_PronounId");

        entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

        entity.Property(e => e.Alias)
            .IsRequired()
            .HasMaxLength(50);

        entity.Property(e => e.Email)
            .IsRequired()
            .HasMaxLength(150);

        entity.Property(e => e.FirstName)
            .IsRequired()
            .HasMaxLength(50);

        entity.Property(e => e.LastName)
            .IsRequired()
            .HasMaxLength(50);

        entity.HasOne(d => d.Incident)
            .WithMany(p => p.NonStaffPeople)
            .HasForeignKey(d => d.IncidentId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_NonStaff_Incidents_Id");

        entity.HasOne(d => d.Pronoun)
            .WithMany(p => p.NonStaffPeople)
            .HasForeignKey(d => d.PronounId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_NonStaff_Pronouns_Id");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<NonStaffPerson> entity);
}