// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using YSecOps.Data.EfCore.Contexts;
using YSecOps.Data.EfCore.Models;

namespace YSecOps.Data.EfCore.Contexts.Configurations
{
    public partial class RadioScheduleConfiguration : IEntityTypeConfiguration<RadioSchedule>
    {
        public void Configure(EntityTypeBuilder<RadioSchedule> entity)
        {
            entity.ToTable("RadioSchedule");

            entity.ToTable(tb => tb.IsTemporal(ttb =>
    {
        ttb.UseHistoryTable("RadioSchedule_HISTORY", "dbo");
        ttb
            .HasPeriodStart("SysStart")
            .HasColumnName("SysStart");
        ttb
            .HasPeriodEnd("SysEnd")
            .HasColumnName("SysEnd");
    }
));

            entity.HasIndex(e => e.LastStaffToHave_Id, "IX_RadioSchedule_LastStaffId");

            entity.HasIndex(e => e.Location_Id, "IX_RadioSchedule_Location");

            entity.HasIndex(e => e.RadioNumber, "IX_RadioSchedule_RadioNumber");

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.IsCharging).HasDefaultValueSql("((0))");

            entity.Property(e => e.RadioNumber)
                .IsRequired()
                .HasMaxLength(20);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RadioSchedule> entity);
    }
}
