// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace YSecOps.Data.EfCore.Contexts.Configurations;

public partial class RadioScheduleConfiguration : IEntityTypeConfiguration<RadioSchedule>
{
    public void Configure(EntityTypeBuilder<RadioSchedule> entity)
    {
        entity.ToTable("RadioSchedule");

        entity.HasIndex(e => e.LastStaffToHave_Id, "IX_RadioSchedule_LastStaffId");

        entity.HasIndex(e => e.Location_Id, "IX_RadioSchedule_Location");

        entity.HasIndex(e => e.RadioNumber, "IX_RadioSchedule_RadioNumber");

        entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

        entity.Property(e => e.IsCharging).HasDefaultValueSql("((0))");

        entity.Property(e => e.RadioNumber)
            .IsRequired()
            .HasMaxLength(20);

        entity.HasOne(d => d.LastStaffToHave)
            .WithMany(p => p.RadioSchedules)
            .HasForeignKey(d => d.LastStaffToHave_Id)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_RadioSchedule_Staff");

        entity.HasOne(d => d.Location)
            .WithMany(p => p.RadioSchedules)
            .HasForeignKey(d => d.Location_Id)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_RadioSchedule_Location");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<RadioSchedule> entity);
}