// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace YSecOps.Data.EfCore.Contexts.Configurations;

public partial class RoleConfiguration : IEntityTypeConfiguration<Role>
{
    public void Configure(EntityTypeBuilder<Role> entity)
    {
        entity.Property(e => e.Role1)
            .HasMaxLength(50)
            .HasColumnName("Role");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Role> entity);
}