// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace YSecOps.Data.EfCore.Contexts.Configurations;

public partial class RoomScheduleConfiguration : IEntityTypeConfiguration<RoomSchedule>
{
    public void Configure(EntityTypeBuilder<RoomSchedule> entity)
    {
        entity.ToTable("RoomSchedule");

        entity.HasIndex(e => new { e.Floor, e.Number }, "IX_RoomSchedule_Floor_Number");

        entity.HasIndex(e => e.Location_Id, "IX_RoomSchedule_Location");

        entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

        entity.Property(e => e.Keys).HasDefaultValueSql("((1))");

        entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(30);

        entity.Property(e => e.ProvidedKeys).HasDefaultValueSql("((4))");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<RoomSchedule> entity);
}