// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace YSecOps.Data.EfCore.Contexts.Configurations;

public partial class ShiftConfiguration : IEntityTypeConfiguration<Shift>
{
    public void Configure(EntityTypeBuilder<Shift> entity)
    {
        entity.ToTable("Shifts");

        entity.HasIndex(e => new { e.CheckedInAt, e.CheckedOutAt }, "IX_Shifts_CheckedInAt_CheckedOutAt");

        entity.HasIndex(e => e.CurrentLocationId, "IX_Shifts_CurrentLocationId");

        entity.HasIndex(e => e.StaffId, "IX_Shifts_StaffId");

        entity.HasIndex(e => new { e.StartAt, e.EndAt }, "IX_Shifts_StartAt_EndAt");

        entity.HasIndex(e => e.StartingLocationId, "IX_Shifts_StartingLocationId");

        entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

        entity.Property(e => e.Notes).HasMaxLength(500);

        entity.HasOne(d => d.CurrentLocation)
            .WithMany(p => p.ShiftCurrentLocations)
            .HasForeignKey(d => d.CurrentLocationId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Shifts_CurrentLocation");

        entity.HasOne(d => d.Staff)
            .WithMany(p => p.Shifts)
            .HasForeignKey(d => d.StaffId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Shifts_Staff");

        entity.HasOne(d => d.StartingLocation)
            .WithMany(p => p.ShiftStartingLocations)
            .HasForeignKey(d => d.StartingLocationId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Shifts_StartingLocation");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Shift> entity);
}