// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace YSecOps.Data.EfCore.Contexts.Configurations;

public partial class StaffTypeConfiguration : IEntityTypeConfiguration<StaffType>
{
    public void Configure(EntityTypeBuilder<StaffType> entity)
    {
        entity.Property(e => e.Description)
            .IsRequired()
            .HasMaxLength(100);

        entity.Property(e => e.Title)
            .IsRequired()
            .HasMaxLength(20);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<StaffType> entity);
}