// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using YSecOps.Data.EfCore.Models;
#nullable disable

namespace YSecOps.Data.EfCore.Contexts
{
    public partial class YoumaconSecurityOpsContext : DbContext
    {
        public YoumaconSecurityOpsContext(DbContextOptions<YoumaconSecurityOpsContext> options)
            : base(options)
        {
        }

        public virtual DbSet<BannedList> BannedLists { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Incident> Incidents { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<NonStaffPeople> NonStaffPeoples { get; set; }
        public virtual DbSet<Pronoun> Pronouns { get; set; }
        public virtual DbSet<RadioSchedule> RadioSchedules { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoomSchedule> RoomSchedules { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<StaffType> StaffTypes { get; set; }
        public virtual DbSet<StaffTypesRole> StaffTypesRoles { get; set; }
        public virtual DbSet<WatchList> WatchLists { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.BannedListConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ContactConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.IncidentConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.LocationConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.NonStaffPeopleConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PronounConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RadioScheduleConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RoleConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RoomScheduleConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ShiftConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.StaffConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.StaffTypeConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.StaffTypesRoleConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.WatchListConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
