// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace YoumaconSecurityOps.Data.EntityFramework.Models
{
    public partial class p_AddStaffRolesResult
    {
    }
}
